import type { Game, Team } from "./types";

/**
 * SAMPLE DATA for the clickable prototype.
 * Teams and venues are real. Player names, statistics, projections, weather and
 * odds are placeholders so the layout can be reviewed. Nothing here should be
 * read as a real evaluation. In production every field comes from the evidence
 * packet with a source and an as-of time.
 */

const T = (id: string, name: string, short: string, abbr: string, record: string, conference: string, color: string): Team => ({
  id, name, short, abbr, record, conference, color,
});

const AS_OF = "2026-09-12T09:15:00-04:00";

export const games: Game[] = [
  // ---------------------------------------------------------------- NOON
  {
    id: "wis-ala",
    division: "FBS",
    away: T("wis", "Wisconsin Badgers", "Wisconsin", "WIS", "1-1", "Big Ten", "#C5050C"),
    home: T("ala", "Alabama Crimson Tide", "Alabama", "ALA", "2-0", "SEC", "#9E1B32"),
    kickoff: "2026-09-12T12:00:00-04:00",
    venue: "Bryant-Denny Stadium",
    city: "Tuscaloosa, AL",
    network: "ABC",
    status: "final",
    score: { home: 31, away: 13, clock: "Final" },
    coverage: "Full",
    whyWatch: "A gap-scheme run game meets an SEC front with two draftable interior players.",
    whyWatchReasons: [
      "Alabama's interior defensive line has two names on early boards and Wisconsin will run right at them.",
      "Wisconsin's left tackle is the visitor's best pro prospect and draws the home edge rusher on most snaps.",
      "Heat index near 100 will test how deep Wisconsin's defensive front rotation really is.",
    ],
    styleLine: "Gap-run offense vs heavy front",
    weather: { windMph: 6, gustMph: 10, windDir: "SW", crosswind: false, precipChance: 10, tempF: 91, feelsLikeF: 99, humidity: 58, stormRisk: "none", roof: "open", surface: "grass", elevationFt: 222, asOf: AS_OF },
    market: { spread: { team: "ALA", line: -17.5, open: -16 }, total: { line: 48.5, open: 49.5 }, books: 9, asOf: "2026-09-12T11:40:00-04:00" },
    prospects: [
      { id: "p-ala-1", name: "Dorian Ashby", team: "ALA", jersey: 92, pos: "DT", cls: "Jr", ht: "6-3", wt: 312, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 1-2", sourceCount: 7, projectionConfidence: "High", traits: ["Two-gap anchor", "Quick first step"], weakness: "Pass-rush plan stalls when first move fails", watchFor: "Whether Wisconsin doubles him on duo and who wins the leverage battle.", stat: "4.5 TFL through 2 games" },
      { id: "p-wis-1", name: "Cal Brenner", team: "WIS", jersey: 71, pos: "OT", cls: "RS Sr", ht: "6-6", wt: 318, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 2-3", sourceCount: 6, projectionConfidence: "Medium", traits: ["Length", "Vertical set patience"], weakness: "Loses balance against inside counters", watchFor: "Third-and-long snaps against speed off the edge.", stat: "0 sacks allowed" },
      { id: "p-ala-2", name: "Reese Okafor", team: "ALA", jersey: 6, pos: "CB", cls: "So", ht: "6-0", wt: 188, draftYear: 2028, eligibilityConfidence: "Medium", tier: "Future", projected: "Not yet eligible", sourceCount: 3, projectionConfidence: "Low", traits: ["Press technique", "Ball skills"], watchFor: "Snaps at boundary corner against Wisconsin's play-action shots.", stat: "2 PBU" },
    ],
    matchups: [
      { a: "Cal Brenner (WIS OT)", b: "Marcus Idowu (ALA EDGE)", why: "Wisconsin's best prospect against Alabama's most productive pass rusher.", evidence: "Idowu aligns wide-left on 61% of pass snaps; Brenner plays left tackle exclusively." },
    ],
    keepAnEyeOn: [
      { name: "Tavian Cole", team: "WIS", note: "True freshman running back getting second-series carries. 2029 eligible." },
    ],
    storylines: ["Wisconsin's offensive coordinator spent three seasons on the Alabama staff.", "Alabama's starting center returns from a two-game injury absence."],
    offense: {
      WIS: { label: "Gap-run, play-action", passRate: 42, neutralPassRate: 46, secondsPerPlay: 29.1, structure: "Pro-style, 12 and 21 personnel", runGame: "Power, counter, duo", passGame: "Play-action boot, deep crossers", successRate: 44, explosiveRate: 9, pressureAllowed: 24, sample: "small" },
      ALA: { label: "Balanced spread", passRate: 55, neutralPassRate: 58, secondsPerPlay: 24.8, structure: "Spread, 11 personnel", runGame: "Inside zone, RPO", passGame: "Quick game, RPO glance", successRate: 52, explosiveRate: 14, pressureAllowed: 19, sample: "small" },
    },
    defense: {
      WIS: { label: "Two-high zone", front: "Odd, 3-4 base", coverage: "Two-high, quarters influence", blitzRate: 22, pressureRate: 31, stuffRate: 18, explosivesAllowed: 11, sample: "small" },
      ALA: { label: "Heavy front, single-high", front: "Even, 4-2-5", coverage: "Single-high, man on third down", blitzRate: 31, pressureRate: 39, stuffRate: 24, explosivesAllowed: 8, sample: "small" },
    },
    pressurePoint: "Wisconsin wants 12-personnel duo runs into a front that has stuffed 24% of rushes. If the gap game stalls, the visitor is in third-and-long against man coverage and a 31% blitz rate.",
    scoreComponents: { draftTalent: 78, directMatchups: 70, futureTalent: 60, competitive: 35, styleContrast: 75, storylines: 60, availability: 90 },
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "tol-bgsu",
    division: "FBS",
    away: T("tol", "Toledo Rockets", "Toledo", "TOL", "2-0", "MAC", "#15397F"),
    home: T("bgsu", "Bowling Green Falcons", "Bowling Green", "BGSU", "1-1", "MAC", "#4F2C1D"),
    kickoff: "2026-09-12T12:00:00-04:00",
    venue: "Doyt Perry Stadium",
    city: "Bowling Green, OH",
    network: "ESPN+",
    status: "final",
    score: { home: 20, away: 27, clock: "Final" },
    coverage: "Full",
    whyWatch: "A MAC edge rusher with a Day 2 grade against a tempo offense that snaps every 22 seconds.",
    whyWatchReasons: ["Toledo's edge rusher is the best pro prospect in the conference.", "Bowling Green's no-huddle pace forces the visitor's front to play without rotation.", "Closest MAC line of the week."],
    styleLine: "Tempo spread vs pressure defense",
    weather: { windMph: 12, gustMph: 17, windDir: "W", crosswind: true, precipChance: 20, tempF: 68, feelsLikeF: 68, humidity: 55, stormRisk: "none", roof: "open", surface: "turf", elevationFt: 692, asOf: AS_OF },
    market: { spread: { team: "TOL", line: -3, open: -3.5 }, total: { line: 55.5, open: 54 }, books: 7, asOf: "2026-09-12T11:40:00-04:00" },
    prospects: [
      { id: "p-tol-1", name: "Jaylen Priddy", team: "TOL", jersey: 9, pos: "EDGE", cls: "Sr", ht: "6-4", wt: 254, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 2-3", sourceCount: 5, projectionConfidence: "Medium", traits: ["Bend", "Long-arm conversion"], weakness: "Run-down discipline on the backside", watchFor: "Whether he can rush from a two-point stance at tempo without losing his get-off.", stat: "3 sacks" },
    ],
    matchups: [{ a: "Jaylen Priddy (TOL EDGE)", b: "Nico Fairbanks (BGSU LT)", why: "A Day 2 rusher against a sophomore tackle making his fourth start.", evidence: "Fairbanks allowed 5 pressures last week; Priddy has won 21% of pass-rush snaps." }],
    keepAnEyeOn: [{ name: "Owen Marsh", team: "BGSU", note: "Redshirt freshman quarterback with a 2029 earliest draft year and a live arm." }],
    storylines: ["Toledo has won four straight in the series."],
    offense: {
      TOL: { label: "Balanced, RPO", passRate: 51, neutralPassRate: 54, secondsPerPlay: 26.5, structure: "Spread, 11 personnel", runGame: "Inside zone, RPO", passGame: "RPO glance, screens", successRate: 47, explosiveRate: 12, pressureAllowed: 22, sample: "small" },
      BGSU: { label: "Fast no-huddle", passRate: 60, neutralPassRate: 63, secondsPerPlay: 21.9, structure: "Air raid influence, 10 and 11 personnel", runGame: "Inside zone, draw", passGame: "Mesh, quick game, screens", successRate: 45, explosiveRate: 13, pressureAllowed: 30, sample: "small" },
    },
    defense: {
      TOL: { label: "Pressure-heavy", front: "Even, 4-2-5", coverage: "Single-high", blitzRate: 36, pressureRate: 41, stuffRate: 21, explosivesAllowed: 10, sample: "small" },
      BGSU: { label: "Bend-don't-break", front: "Odd, 3-3-5", coverage: "Two-high", blitzRate: 19, pressureRate: 26, stuffRate: 15, explosivesAllowed: 14, sample: "small" },
    },
    pressurePoint: "Bowling Green's pace against Toledo's blitz rate. Tempo teams usually reduce blitzing; if Toledo keeps sending five, Priddy gets one-on-ones all afternoon.",
    scoreComponents: { draftTalent: 45, directMatchups: 65, futureTalent: 40, competitive: 80, styleContrast: 70, storylines: 30, availability: 70 },
    reportAsOf: AS_OF,
    source: "sample",
  },

  // ----------------------------------------------------------- AFTERNOON
  {
    id: "sdsu-ndsu",
    division: "FCS",
    away: T("sdsu", "South Dakota State Jackrabbits", "South Dakota St", "SDSU", "2-0", "MVFC", "#0033A0"),
    home: T("ndsu", "North Dakota State Bison", "North Dakota St", "NDSU", "2-0", "MVFC", "#005643"),
    kickoff: "2026-09-12T15:00:00-04:00",
    venue: "Fargodome",
    city: "Fargo, ND",
    network: "ESPN2",
    status: "live",
    score: { home: 14, away: 10, clock: "2nd 4:12" },
    coverage: "Standard",
    whyWatch: "The most NFL talent on any FCS field this year, indoors, with three offensive linemen on draft boards.",
    whyWatchReasons: [
      "Both lines carry draft-eligible starters. This is the best FCS trench matchup of the season.",
      "North Dakota State's tight end is the top FCS prospect at his position.",
      "Fixed roof means the game is decided purely by scheme and personnel.",
    ],
    styleLine: "Power run vs power run",
    weather: { windMph: 14, gustMph: 22, windDir: "NW", crosswind: true, precipChance: 40, tempF: 61, feelsLikeF: 61, humidity: 48, stormRisk: "none", roof: "fixed", surface: "turf", elevationFt: 905, asOf: AS_OF },
    market: { spread: { team: "NDSU", line: -2.5, open: -3 }, total: { line: 44.5, open: 44.5 }, books: 5, asOf: "2026-09-12T14:50:00-04:00" },
    prospects: [
      { id: "p-ndsu-1", name: "Hollis Reinke", team: "NDSU", jersey: 85, pos: "TE", cls: "Sr", ht: "6-5", wt: 251, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 3-4", sourceCount: 6, projectionConfidence: "Medium", traits: ["In-line blocking", "Seam routes"], watchFor: "Y-off alignments and whether SDSU's safeties bite on play-action.", stat: "9 rec, 141 yds" },
      { id: "p-sdsu-1", name: "Brody Lindqvist", team: "SDSU", jersey: 74, pos: "OG", cls: "RS Sr", ht: "6-4", wt: 322, draftYear: 2027, eligibilityConfidence: "High", tier: "Emerging", projected: "Round 5-7", sourceCount: 3, projectionConfidence: "Low", traits: ["Drive blocking"], weakness: "Lateral range on outside zone", watchFor: "Double teams with the center on duo.", stat: "412 snaps, 2 pressures allowed" },
      { id: "p-ndsu-2", name: "Kade Ostrowski", team: "NDSU", jersey: 58, pos: "IOL", cls: "Jr", ht: "6-4", wt: 308, draftYear: 2028, eligibilityConfidence: "Medium", tier: "Future", projected: "Not yet eligible", sourceCount: 2, projectionConfidence: "Low", traits: ["Combination blocks"], watchFor: "Pulls on counter.", stat: "Starting center" },
      { id: "p-sdsu-2", name: "Emeka Nwosu", team: "SDSU", jersey: 3, pos: "S", cls: "Sr", ht: "6-1", wt: 205, draftYear: 2027, eligibilityConfidence: "High", tier: "Sleeper", projected: "Round 7 to UDFA", sourceCount: 2, projectionConfidence: "Low", traits: ["Box tackling"], weakness: "Deep-third range", watchFor: "How often he is asked to cover Reinke in the seam.", stat: "24 tackles" },
    ],
    matchups: [
      { a: "Hollis Reinke (NDSU TE)", b: "Emeka Nwosu (SDSU S)", why: "The best FCS tight end against a box safety whose coverage range is the question.", evidence: "Nwosu has played 61% of snaps within 8 yards of the line." },
      { a: "Brody Lindqvist (SDSU OG)", b: "NDSU interior front", why: "Drive blocker against a three-man front that stunts on early downs.", evidence: "NDSU stunts on 38% of first-down runs (charting, 2 games)." },
    ],
    keepAnEyeOn: [{ name: "Cooper Vance", team: "SDSU", note: "Sophomore quarterback, former FBS transfer, 2028 eligible." }],
    storylines: ["Twelfth straight meeting with both teams ranked in the FCS top five.", "SDSU's head coach played at NDSU."],
    offense: {
      SDSU: { label: "Power run, 12 personnel", passRate: 40, neutralPassRate: 44, secondsPerPlay: 28.7, structure: "Pro-style, 12 and 13 personnel", runGame: "Duo, power, counter", passGame: "Play-action, deep over", successRate: 49, explosiveRate: 10, pressureAllowed: 20, sample: "small" },
      NDSU: { label: "Power run, QB run", passRate: 38, neutralPassRate: 43, secondsPerPlay: 29.9, structure: "Pro-style, option elements", runGame: "Power, counter, QB power", passGame: "Play-action boot", successRate: 51, explosiveRate: 11, pressureAllowed: 17, sample: "small" },
    },
    defense: {
      SDSU: { label: "Odd front, two-high", front: "Odd, 3-4", coverage: "Two-high", blitzRate: 24, pressureRate: 30, stuffRate: 22, explosivesAllowed: 9, sample: "small" },
      NDSU: { label: "Odd front, stunts", front: "Odd, 3-3-5", coverage: "Coverage family unavailable (no charting)", blitzRate: 27, pressureRate: 33, stuffRate: 25, explosivesAllowed: 8, sample: "small" },
    },
    pressurePoint: "Two power-run teams with sub-45% neutral pass rates. Possession count will be low; the first team to win a short-yardage down in the fourth quarter probably wins.",
    scoreComponents: { draftTalent: 62, directMatchups: 85, futureTalent: 55, competitive: 90, styleContrast: 30, storylines: 70, availability: 85 },
    gaps: ["Coverage family for NDSU not charted; season totals only.", "Snap counts unavailable for NDSU skill players."],
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "ten-uga",
    division: "FBS",
    away: T("ten", "Tennessee Volunteers", "Tennessee", "TEN", "2-0", "SEC", "#FF8200"),
    home: T("uga", "Georgia Bulldogs", "Georgia", "UGA", "2-0", "SEC", "#BA0C2F"),
    kickoff: "2026-09-12T15:30:00-04:00",
    venue: "Sanford Stadium",
    city: "Athens, GA",
    network: "CBS",
    status: "live",
    score: { home: 7, away: 3, clock: "1st 3:44" },
    coverage: "Full",
    whyWatch: "Five likely picks, a first-round edge rusher, and a tempo offense trying to outrun a defense that substitutes constantly.",
    whyWatchReasons: [
      "Georgia's edge rusher is a consensus top-15 pick and lines up over Tennessee's weakest tackle.",
      "Tennessee's receiver is the fastest player on either roster and Georgia plays a lot of man coverage.",
      "Storm cells forecast for the second half could put a lightning delay on the table.",
    ],
    styleLine: "Tempo spread vs deep, rotating defense",
    weather: { windMph: 9, gustMph: 21, windDir: "S", crosswind: false, precipChance: 65, precipWindow: "after 5 PM", tempF: 84, feelsLikeF: 91, humidity: 70, stormRisk: "watch", roof: "open", surface: "grass", elevationFt: 650, asOf: AS_OF },
    market: { spread: { team: "UGA", line: -6.5, open: -7.5 }, total: { line: 52.5, open: 55 }, books: 11, asOf: "2026-09-12T15:20:00-04:00" },
    prospects: [
      { id: "p-uga-1", name: "Trey Bellamy", team: "UGA", jersey: 4, pos: "EDGE", cls: "Jr", ht: "6-5", wt: 258, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 1, top 15", sourceCount: 9, projectionConfidence: "High", traits: ["First-step explosion", "Inside counter"], weakness: "Can get washed on down blocks", watchFor: "His alignment: wide-9 on passing downs vs a tight 5-tech on early downs.", stat: "4 sacks, 11 pressures" },
      { id: "p-ten-1", name: "Deshawn Wilkes", team: "TEN", jersey: 1, pos: "WR", cls: "Jr", ht: "6-1", wt: 194, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 1-2", sourceCount: 8, projectionConfidence: "High", traits: ["Vertical speed", "Late hands"], weakness: "Contested catches", watchFor: "Whether Georgia travels its top corner with him or keeps sides.", stat: "11 rec, 248 yds, 3 TD" },
      { id: "p-uga-2", name: "Malik Thornton", team: "UGA", jersey: 10, pos: "LB", cls: "Sr", ht: "6-2", wt: 236, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 2-3", sourceCount: 7, projectionConfidence: "Medium", traits: ["Sideline range", "Blitz timing"], watchFor: "Coverage against Tennessee's running back on option routes.", stat: "18 tackles" },
      { id: "p-ten-2", name: "Grady Holcomb", team: "TEN", jersey: 55, pos: "C", cls: "RS Sr", ht: "6-3", wt: 305, draftYear: 2027, eligibilityConfidence: "High", tier: "Emerging", projected: "Round 4-6", sourceCount: 4, projectionConfidence: "Medium", traits: ["Snap-to-set quickness"], watchFor: "Handling Georgia's nose on tempo plays without help.", stat: "0 pressures allowed" },
      { id: "p-uga-3", name: "Jaxon Reeves", team: "UGA", jersey: 15, pos: "QB", cls: "So", ht: "6-3", wt: 215, draftYear: 2028, eligibilityConfidence: "Medium", tier: "Future", projected: "Not yet eligible", sourceCount: 5, projectionConfidence: "Low", traits: ["Arm talent", "Pocket movement"], watchFor: "Decision speed against Tennessee's simulated pressures.", stat: "68% comp, 6 TD" },
    ],
    matchups: [
      { a: "Trey Bellamy (UGA EDGE)", b: "Rowan Pike (TEN RT)", why: "A top-15 pick against a right tackle who has allowed the most pressures on the line.", evidence: "Pike allowed 7 pressures in two games; Bellamy rushes from the offense's right on 58% of snaps." },
      { a: "Deshawn Wilkes (TEN WR)", b: "Ellis Barrow (UGA CB)", why: "Speed against Georgia's press corner.", evidence: "Georgia has played man on 44% of third downs. Barrow allowed 1 catch of 20+ yards last season." },
    ],
    keepAnEyeOn: [
      { name: "Kamari Blount", team: "TEN", note: "True freshman corner, five-star recruit, first career start. 2029 eligible." },
      { name: "Silas Whitfield", team: "UGA", note: "Transfer receiver returning to face his former team." },
    ],
    storylines: ["Georgia's receiver Silas Whitfield transferred from Tennessee last winter.", "Tennessee has not won in Athens since 2016.", "Georgia's defensive coordinator was Tennessee's linebackers coach from 2019 to 2021."],
    offense: {
      TEN: { label: "Fast spread, vertical", passRate: 54, neutralPassRate: 57, secondsPerPlay: 20.4, structure: "Spread, 10 and 11 personnel, no-huddle", runGame: "Inside zone, QB counter", passGame: "Verticals, RPO glance, screens", successRate: 50, explosiveRate: 16, pressureAllowed: 21, sample: "small" },
      UGA: { label: "Pro spread, play-action", passRate: 52, neutralPassRate: 55, secondsPerPlay: 26.8, structure: "Pro-style spread, 11 and 12 personnel", runGame: "Outside zone, counter", passGame: "Play-action, dropback, motion-heavy", successRate: 53, explosiveRate: 13, pressureAllowed: 16, sample: "small" },
    },
    defense: {
      TEN: { label: "Simulated pressure", front: "Even, 4-2-5", coverage: "Single-high, quarters on early downs", blitzRate: 28, pressureRate: 34, stuffRate: 19, explosivesAllowed: 12, sample: "small" },
      UGA: { label: "Multiple, man-heavy", front: "Multiple, 3-down base", coverage: "Man 44% on third down, two-high early", blitzRate: 30, pressureRate: 42, stuffRate: 26, explosivesAllowed: 7, sample: "small" },
    },
    pressurePoint: "Tennessee snaps the ball every 20 seconds; Georgia rotates 10 defensive linemen. If the tempo prevents substitution, Georgia's pressure rate drops and Wilkes sees single coverage deep.",
    scoreComponents: { draftTalent: 92, directMatchups: 88, futureTalent: 80, competitive: 75, styleContrast: 80, storylines: 85, availability: 95 },
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "nd-pur",
    division: "FBS",
    away: T("nd", "Notre Dame Fighting Irish", "Notre Dame", "ND", "1-1", "Independent", "#0C2340"),
    home: T("pur", "Purdue Boilermakers", "Purdue", "PUR", "1-1", "Big Ten", "#CEB888"),
    kickoff: "2026-09-12T15:30:00-04:00",
    venue: "Ross-Ade Stadium",
    city: "West Lafayette, IN",
    network: "NBC",
    status: "live",
    score: { home: 0, away: 10, clock: "1st 1:02" },
    coverage: "Full",
    whyWatch: "Notre Dame's tackle pair is the best in the country and Purdue blitzes more than anyone in the Big Ten.",
    whyWatchReasons: ["Two draftable Notre Dame tackles against a 40% blitz rate.", "Purdue's slot receiver is a sleeper with elite short-area quickness.", "Crosswind at 18 mph will shape the kicking game late."],
    styleLine: "Pro-style run game vs blitz-heavy defense",
    weather: { windMph: 18, gustMph: 26, windDir: "W", crosswind: true, precipChance: 15, tempF: 66, feelsLikeF: 66, humidity: 50, stormRisk: "none", roof: "open", surface: "turf", elevationFt: 610, asOf: AS_OF },
    market: { spread: { team: "ND", line: -13.5, open: -14.5 }, total: { line: 49.5, open: 51 }, books: 10, asOf: "2026-09-12T15:20:00-04:00" },
    prospects: [
      { id: "p-nd-1", name: "Everett Kalu", team: "ND", jersey: 76, pos: "OT", cls: "Sr", ht: "6-7", wt: 325, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 1", sourceCount: 9, projectionConfidence: "High", traits: ["Anchor", "Recovery strength"], watchFor: "Picking up twists when Purdue sends the nickel.", stat: "1 pressure allowed" },
      { id: "p-nd-2", name: "Luca Ferrante", team: "ND", jersey: 70, pos: "OT", cls: "Jr", ht: "6-6", wt: 310, draftYear: 2027, eligibilityConfidence: "Medium", tier: "Established", projected: "Round 2", sourceCount: 6, projectionConfidence: "Medium", traits: ["Athleticism in space"], weakness: "Hand placement", watchFor: "Reach blocks on outside zone.", stat: "2 pressures allowed" },
      { id: "p-pur-1", name: "Rocco Delaney", team: "PUR", jersey: 13, pos: "WR", cls: "Sr", ht: "5-10", wt: 182, draftYear: 2027, eligibilityConfidence: "High", tier: "Sleeper", projected: "Round 6 to UDFA", sourceCount: 2, projectionConfidence: "Low", traits: ["Short-area quickness"], weakness: "Size and contested wins", watchFor: "Option routes against Notre Dame's nickel.", stat: "14 rec, 9 first downs" },
    ],
    matchups: [{ a: "Everett Kalu (ND OT)", b: "Purdue twist games", why: "Round 1 tackle against the Big Ten's highest blitz rate.", evidence: "Purdue blitzed 40% of dropbacks in week 2." }],
    keepAnEyeOn: [{ name: "Beau Tillman", team: "ND", note: "Sophomore safety with three interceptions in two games. 2028 eligible." }],
    storylines: ["Purdue's head coach was Notre Dame's offensive coordinator in 2022."],
    offense: {
      ND: { label: "Pro-style, multiple", passRate: 48, neutralPassRate: 52, secondsPerPlay: 27.2, structure: "Multiple, 11 and 12 personnel", runGame: "Outside zone, counter", passGame: "Play-action, boot", successRate: 51, explosiveRate: 12, pressureAllowed: 14, sample: "small" },
      PUR: { label: "Spread, quick game", passRate: 58, neutralPassRate: 60, secondsPerPlay: 24.1, structure: "Spread, 11 personnel", runGame: "Inside zone", passGame: "Quick game, mesh", successRate: 44, explosiveRate: 9, pressureAllowed: 28, sample: "small" },
    },
    defense: {
      ND: { label: "Multiple, disguised", front: "Multiple", coverage: "Two-high shells, rotates late", blitzRate: 25, pressureRate: 36, stuffRate: 23, explosivesAllowed: 8, sample: "small" },
      PUR: { label: "Blitz-heavy", front: "Even, 4-2-5", coverage: "Single-high, man behind blitz", blitzRate: 40, pressureRate: 38, stuffRate: 17, explosivesAllowed: 15, sample: "small" },
    },
    pressurePoint: "Purdue must blitz to generate pressure but Notre Dame's tackles have allowed 3 pressures combined. If blitzes do not get home, single-high man behind them gives up explosives.",
    scoreComponents: { draftTalent: 80, directMatchups: 72, futureTalent: 55, competitive: 40, styleContrast: 65, storylines: 45, availability: 95 },
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "fsu-gvsu",
    division: "DII",
    away: T("fsu", "Ferris State Bulldogs", "Ferris State", "FSU", "2-0", "GLIAC", "#BA0C2F"),
    home: T("gvsu", "Grand Valley State Lakers", "Grand Valley St", "GVSU", "2-0", "GLIAC", "#0032A0"),
    kickoff: "2026-09-12T16:00:00-04:00",
    venue: "Lubbers Stadium",
    city: "Allendale, MI",
    network: "FloSports",
    status: "upcoming",
    coverage: "Limited",
    whyWatch: "The two best programs in Division II, with a Ferris State edge rusher who was invited to a spring NFL showcase.",
    whyWatchReasons: ["Best rivalry in Division II, both unbeaten.", "Ferris State edge rusher has verified NFL showcase interest.", "Lower-division beta: report has stated gaps."],
    styleLine: "Option-influenced offense vs aggressive front",
    weather: { windMph: 16, gustMph: 24, windDir: "W", crosswind: true, precipChance: 25, tempF: 64, feelsLikeF: 64, humidity: 52, stormRisk: "none", roof: "open", surface: "turf", elevationFt: 640, asOf: AS_OF },
    market: { asOf: AS_OF },
    prospects: [
      { id: "p-fsu-1", name: "Darius Pettigrew", team: "FSU", jersey: 44, pos: "EDGE", cls: "Sr", ht: "6-3", wt: 248, draftYear: 2027, eligibilityConfidence: "Medium", tier: "Sleeper", projected: "Round 7 to UDFA", sourceCount: 2, projectionConfidence: "Low", traits: ["Motor", "Power rush"], weakness: "Level of competition", watchFor: "Whether he wins with something other than effort against GVSU's tackles.", stat: "Stats not yet verified" },
    ],
    matchups: [],
    keepAnEyeOn: [{ name: "Tommy Ruggiero", team: "GVSU", note: "Junior quarterback, dual-threat, no draft projection on file." }],
    storylines: ["The Anchor-Bone Classic. Winner has gone to the DII national semifinal in each of the last five seasons."],
    offense: {
      FSU: { label: "Option-influenced spread", passRate: 40, neutralPassRate: 0, secondsPerPlay: 0, structure: "Spread option", runGame: "Zone read, QB power", passGame: "RPO", successRate: 0, explosiveRate: 0, pressureAllowed: 0, sample: "unavailable" },
      GVSU: { label: "Balanced pro-style", passRate: 50, neutralPassRate: 0, secondsPerPlay: 0, structure: "Pro-style", runGame: "Zone", passGame: "Play-action", successRate: 0, explosiveRate: 0, pressureAllowed: 0, sample: "unavailable" },
    },
    defense: {
      FSU: { label: "Aggressive front", front: "Even", coverage: "Unavailable", blitzRate: 0, pressureRate: 0, stuffRate: 0, explosivesAllowed: 0, sample: "unavailable" },
      GVSU: { label: "Unavailable", front: "Unavailable", coverage: "Unavailable", blitzRate: 0, pressureRate: 0, stuffRate: 0, explosivesAllowed: 0, sample: "unavailable" },
    },
    pressurePoint: "Tendency metrics are unavailable without play-by-play. Scheme labels above come from box scores and program history only.",
    scoreComponents: { draftTalent: 30, directMatchups: 20, futureTalent: 25, competitive: 95, styleContrast: 40, storylines: 80, availability: 55 },
    gaps: ["No play-by-play feed. Tendencies are unavailable.", "No widely available betting line.", "Roster verified from school site on 9/10; depth chart not published.", "Prospect stats pending verification."],
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "ncc-mtu",
    division: "DIII",
    away: T("ncc", "North Central Cardinals", "North Central", "NCC", "1-0", "CCIW", "#C8102E"),
    home: T("mtu", "Mount Union Purple Raiders", "Mount Union", "MTU", "1-0", "OAC", "#582C83"),
    kickoff: "2026-09-12T13:00:00-04:00",
    venue: "Mount Union Stadium",
    city: "Alliance, OH",
    network: "Local stream",
    status: "final",
    score: { home: 24, away: 35, clock: "Final" },
    coverage: "Limited",
    whyWatch: "A Division III national-title preview. No NFL projections on file; watch it for the football.",
    whyWatchReasons: ["The two winningest DIII programs of the last decade.", "North Central's receiver led all of DIII in yards last season.", "No current NFL projections. This is listed for discovery, not draft value."],
    styleLine: "Spread passing vs option run game",
    weather: { windMph: 11, gustMph: 15, windDir: "W", crosswind: false, precipChance: 20, tempF: 67, feelsLikeF: 67, humidity: 50, stormRisk: "none", roof: "open", surface: "turf", elevationFt: 1085, asOf: AS_OF },
    market: { asOf: AS_OF },
    prospects: [
      { id: "p-ncc-1", name: "Andre Voss", team: "NCC", jersey: 8, pos: "WR", cls: "Sr", ht: "6-2", wt: 200, draftYear: 2027, eligibilityConfidence: "Medium", tier: "Watch only", projected: "No projection", sourceCount: 0, projectionConfidence: "Low", traits: ["Production"], watchFor: "Release against press. No projection is offered because no evaluator has published one.", stat: "1,412 yds last season" },
    ],
    matchups: [],
    keepAnEyeOn: [],
    storylines: ["These programs met in three of the last four Stagg Bowls."],
    offense: {
      NCC: { label: "Spread passing", passRate: 0, neutralPassRate: 0, secondsPerPlay: 0, structure: "Spread", runGame: "Unavailable", passGame: "Unavailable", successRate: 0, explosiveRate: 0, pressureAllowed: 0, sample: "unavailable" },
      MTU: { label: "Option run", passRate: 0, neutralPassRate: 0, secondsPerPlay: 0, structure: "Option", runGame: "Unavailable", passGame: "Unavailable", successRate: 0, explosiveRate: 0, pressureAllowed: 0, sample: "unavailable" },
    },
    defense: {
      NCC: { label: "Unavailable", front: "Unavailable", coverage: "Unavailable", blitzRate: 0, pressureRate: 0, stuffRate: 0, explosivesAllowed: 0, sample: "unavailable" },
      MTU: { label: "Unavailable", front: "Unavailable", coverage: "Unavailable", blitzRate: 0, pressureRate: 0, stuffRate: 0, explosivesAllowed: 0, sample: "unavailable" },
    },
    pressurePoint: "Tendency metrics unavailable. Style labels are from program history.",
    scoreComponents: { draftTalent: 10, directMatchups: 10, futureTalent: 20, competitive: 90, styleContrast: 60, storylines: 75, availability: 40 },
    gaps: ["No play-by-play or box-score feed during the game.", "No betting market.", "No published NFL projections."],
    reportAsOf: AS_OF,
    source: "sample",
  },

  // --------------------------------------------------------------- PRIME
  {
    id: "mich-okla",
    division: "FBS",
    away: T("mich", "Michigan Wolverines", "Michigan", "MICH", "2-0", "Big Ten", "#00274C"),
    home: T("okla", "Oklahoma Sooners", "Oklahoma", "OKLA", "2-0", "SEC", "#841617"),
    kickoff: "2026-09-12T19:30:00-04:00",
    venue: "Gaylord Family Oklahoma Memorial Stadium",
    city: "Norman, OK",
    network: "ABC",
    status: "upcoming",
    coverage: "Full",
    whyWatch: "A future first-round quarterback faces a pressure-oriented defense, and the interior line matchup has draftable talent on both sides.",
    whyWatchReasons: [
      "Michigan's quarterback is a projected 2028 first-rounder facing the highest pressure rate in the SEC.",
      "Oklahoma's defensive tackle and Michigan's right guard are both Round 2 names and will meet on most snaps.",
      "The tempo gap is the widest on the slate: Michigan huddles, Oklahoma snaps every 22 seconds. Possession count decides this.",
    ],
    styleLine: "Slow pro-style vs fast spread, pressure defense",
    weather: { windMph: 21, gustMph: 31, windDir: "S", crosswind: true, precipChance: 35, precipWindow: "9 to 11 PM", tempF: 88, feelsLikeF: 94, humidity: 48, stormRisk: "watch", roof: "open", surface: "grass", elevationFt: 1180, asOf: AS_OF },
    market: { spread: { team: "OKLA", line: -3, open: -1.5 }, total: { line: 47.5, open: 50.5 }, moneyline: { home: -150, away: 130 }, books: 12, asOf: "2026-09-12T11:40:00-04:00" },
    prospects: [
      { id: "p-mich-1", name: "Bryce Halloran", team: "MICH", jersey: 7, pos: "QB", cls: "So", ht: "6-4", wt: 222, draftYear: 2028, eligibilityConfidence: "High", tier: "Future", projected: "2028 Round 1 (early boards)", sourceCount: 6, projectionConfidence: "Medium", traits: ["Arm strength", "Off-platform accuracy"], weakness: "Holds the ball against disguised pressure", watchFor: "Time to throw when Oklahoma shows six and drops two.", stat: "71% comp, 7 TD, 1 INT" },
      { id: "p-okla-1", name: "Tavares Boone", team: "OKLA", jersey: 95, pos: "DT", cls: "Sr", ht: "6-3", wt: 306, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 2", sourceCount: 8, projectionConfidence: "High", traits: ["Penetration", "Hand violence"], weakness: "Loses gap integrity chasing plays", watchFor: "Alignment on Michigan's right guard in 3-tech; whether Michigan slides protection to him.", stat: "3 sacks, 9 pressures" },
      { id: "p-mich-2", name: "Owen Castellano", team: "MICH", jersey: 66, pos: "OG", cls: "Sr", ht: "6-5", wt: 318, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 2-3", sourceCount: 7, projectionConfidence: "Medium", traits: ["Anchor", "Double-team climb"], weakness: "Reach on outside zone", watchFor: "One-on-ones with Boone on third down.", stat: "0 sacks allowed" },
      { id: "p-okla-2", name: "Kendall Ruiz", team: "OKLA", jersey: 2, pos: "CB", cls: "Jr", ht: "6-0", wt: 190, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 1-2", sourceCount: 8, projectionConfidence: "High", traits: ["Press technique", "Transition"], watchFor: "Whether he shadows Michigan's X receiver on the boundary.", stat: "2 INT" },
      { id: "p-mich-3", name: "Jonah Whitcomb", team: "MICH", jersey: 21, pos: "RB", cls: "Jr", ht: "5-11", wt: 214, draftYear: 2027, eligibilityConfidence: "High", tier: "Emerging", projected: "Round 4-5", sourceCount: 4, projectionConfidence: "Medium", traits: ["Contact balance", "Pass protection"], watchFor: "Blitz pickup against Oklahoma's linebacker fire.", stat: "232 yds, 5.8 ypc" },
      { id: "p-okla-3", name: "Micah Ledbetter", team: "OKLA", jersey: 11, pos: "LB", cls: "Sr", ht: "6-1", wt: 232, draftYear: 2027, eligibilityConfidence: "High", tier: "Emerging", projected: "Round 4-6", sourceCount: 3, projectionConfidence: "Low", traits: ["Blitz timing"], weakness: "Coverage drops", watchFor: "A-gap blitzes against Whitcomb.", stat: "2 sacks" },
      { id: "p-okla-4", name: "Cyrus Nakamura", team: "OKLA", jersey: 17, pos: "WR", cls: "Fr", ht: "6-2", wt: 195, draftYear: 2029, eligibilityConfidence: "High", tier: "Future", projected: "Not yet eligible", sourceCount: 2, projectionConfidence: "Low", traits: ["Contested catch"], watchFor: "Red-zone fades. Former five-star recruit.", stat: "6 rec, 2 TD" },
    ],
    matchups: [
      { a: "Owen Castellano (MICH OG)", b: "Tavares Boone (OKLA DT)", why: "Round 2 guard against Round 2 tackle. Both win with power, so the first punch decides most reps.", evidence: "Boone aligns as 3-tech to the offense's right on 64% of snaps; Castellano is Michigan's right guard." },
      { a: "Bryce Halloran (MICH QB)", b: "Oklahoma disguise package", why: "The quarterback's biggest weakness meets the defense's biggest strength.", evidence: "Oklahoma leads the SEC in pressure rate (44%) and shows simulated pressure on 19% of dropbacks." },
      { a: "Jonah Whitcomb (MICH RB)", b: "Micah Ledbetter (OKLA LB)", why: "Blitz pickup by a back rated for pass protection against an A-gap blitzer.", evidence: "Ledbetter has 6 pressures on 22 blitzes." },
    ],
    keepAnEyeOn: [
      { name: "Cyrus Nakamura", team: "OKLA", note: "True freshman receiver, former five-star, red-zone role. 2029 eligible." },
      { name: "Dante Ferrell", team: "MICH", note: "Transfer edge rusher returning to Oklahoma, where he played from 2023 to 2025." },
      { name: "Nate Oyelaran", team: "OKLA", note: "Sophomore safety, three starts, 2028 eligible. Coaches moved him to nickel this week." },
    ],
    storylines: [
      "Michigan edge rusher Dante Ferrell transferred from Oklahoma in January and faces his former teammates.",
      "Oklahoma's offensive coordinator was Michigan's quarterbacks coach in 2021.",
      "Michigan's starting left tackle is questionable (ankle). Depth chart last updated 9/11 at 6 PM.",
      "First meeting since the 1976 Orange Bowl.",
    ],
    offense: {
      MICH: { label: "Slow pro-style, huddle", passRate: 46, neutralPassRate: 49, secondsPerPlay: 30.2, structure: "Pro-style, 12 and 21 personnel, under center", runGame: "Duo, power, counter", passGame: "Play-action, deep crossers, boot", successRate: 50, explosiveRate: 11, pressureAllowed: 18, sample: "small" },
      OKLA: { label: "Fast spread, RPO", passRate: 57, neutralPassRate: 60, secondsPerPlay: 22.1, structure: "Spread, 11 and 10 personnel, no-huddle", runGame: "Inside zone, RPO, QB draw", passGame: "RPO glance, quick game, verticals", successRate: 48, explosiveRate: 15, pressureAllowed: 25, sample: "small" },
    },
    defense: {
      MICH: { label: "Two-high, light blitz", front: "Even, 4-2-5", coverage: "Two-high, quarters", blitzRate: 18, pressureRate: 33, stuffRate: 22, explosivesAllowed: 9, sample: "small" },
      OKLA: { label: "Pressure, disguise", front: "Multiple, odd-stem", coverage: "Single-high behind pressure, two-high shell pre-snap", blitzRate: 38, pressureRate: 44, stuffRate: 20, explosivesAllowed: 13, sample: "small" },
    },
    pressurePoint: "A huddle offense at 30 seconds per play versus a 22-second no-huddle. Michigan wants nine possessions; Oklahoma wants fourteen. Michigan's pass protection against a 44% pressure rate is the swing factor: if Halloran gets time on play-action, Michigan's slow game works. If not, Oklahoma's tempo wins the possession battle.",
    scoreComponents: { draftTalent: 90, directMatchups: 92, futureTalent: 95, competitive: 85, styleContrast: 95, storylines: 90, availability: 95 },
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "mont-ida",
    division: "FCS",
    away: T("mont", "Montana Grizzlies", "Montana", "MONT", "2-0", "Big Sky", "#70002E"),
    home: T("ida", "Idaho Vandals", "Idaho", "IDA", "1-1", "Big Sky", "#B3A369"),
    kickoff: "2026-09-12T21:00:00-04:00",
    venue: "Kibbie Dome",
    city: "Moscow, ID",
    network: "ESPN+",
    status: "upcoming",
    coverage: "Standard",
    whyWatch: "Idaho's quarterback is the FCS's most-discussed transfer target and Montana's linebacker is a Day 3 name.",
    whyWatchReasons: ["Idaho's quarterback has FBS-caliber tools and an FCS schedule.", "Montana's linebacker is a verified Day 3 prospect.", "Indoors, so weather is not a factor."],
    styleLine: "Vertical passing vs sound zone defense",
    weather: { windMph: 8, gustMph: 12, windDir: "N", crosswind: false, precipChance: 10, tempF: 58, feelsLikeF: 58, humidity: 40, stormRisk: "none", roof: "fixed", surface: "turf", elevationFt: 2580, asOf: AS_OF },
    market: { spread: { team: "MONT", line: -4.5, open: -4 }, total: { line: 51.5, open: 51 }, books: 4, asOf: "2026-09-12T11:40:00-04:00" },
    prospects: [
      { id: "p-mont-1", name: "Wyatt Lund", team: "MONT", jersey: 42, pos: "LB", cls: "Sr", ht: "6-2", wt: 238, draftYear: 2027, eligibilityConfidence: "High", tier: "Emerging", projected: "Round 5-7", sourceCount: 4, projectionConfidence: "Medium", traits: ["Downhill trigger"], weakness: "Change of direction in space", watchFor: "Coverage drops against Idaho's crossers.", stat: "21 tackles, 1 INT" },
      { id: "p-ida-1", name: "Rylan Sato", team: "IDA", jersey: 12, pos: "QB", cls: "Jr", ht: "6-3", wt: 218, draftYear: 2028, eligibilityConfidence: "Medium", tier: "Emerging", projected: "Range unclear (2 sources)", sourceCount: 2, projectionConfidence: "Low", traits: ["Arm talent", "Pocket presence"], watchFor: "Throws outside the numbers against Montana's off coverage.", stat: "64% comp, 5 TD" },
    ],
    matchups: [{ a: "Rylan Sato (IDA QB)", b: "Wyatt Lund (MONT LB)", why: "Idaho attacks the middle of the field; Lund's coverage is the question on his profile.", evidence: "Idaho throws between the hashes on 41% of attempts." }],
    keepAnEyeOn: [],
    storylines: ["Little Brown Stein rivalry, played annually since 1938 with gaps."],
    offense: {
      MONT: { label: "Balanced, tempo", passRate: 52, neutralPassRate: 55, secondsPerPlay: 24.5, structure: "Spread", runGame: "Zone", passGame: "Quick game, verticals", successRate: 47, explosiveRate: 12, pressureAllowed: 22, sample: "small" },
      IDA: { label: "Vertical passing", passRate: 62, neutralPassRate: 65, secondsPerPlay: 25.0, structure: "Spread, 11 personnel", runGame: "Inside zone", passGame: "Verticals, crossers", successRate: 46, explosiveRate: 15, pressureAllowed: 29, sample: "small" },
    },
    defense: {
      MONT: { label: "Sound zone", front: "Odd, 3-4", coverage: "Two-high zone", blitzRate: 20, pressureRate: 28, stuffRate: 20, explosivesAllowed: 10, sample: "small" },
      IDA: { label: "Man pressure", front: "Even, 4-2-5", coverage: "Single-high", blitzRate: 33, pressureRate: 35, stuffRate: 16, explosivesAllowed: 14, sample: "small" },
    },
    pressurePoint: "Idaho's vertical passing game against a Montana defense that gives up little over the top. Expect a lot of check-downs and whether Lund can cover them.",
    scoreComponents: { draftTalent: 40, directMatchups: 55, futureTalent: 60, competitive: 70, styleContrast: 55, storylines: 50, availability: 70 },
    gaps: ["Snap counts unavailable.", "Depth chart from school release only."],
    reportAsOf: AS_OF,
    source: "sample",
  },

  // ----------------------------------------------------------- LATE NIGHT
  {
    id: "bsu-orst",
    division: "FBS",
    away: T("bsu", "Boise State Broncos", "Boise State", "BSU", "2-0", "Mountain West", "#0033A0"),
    home: T("orst", "Oregon State Beavers", "Oregon State", "ORST", "1-1", "Pac-12", "#DC4405"),
    kickoff: "2026-09-12T22:30:00-04:00",
    venue: "Reser Stadium",
    city: "Corvallis, OR",
    network: "CW",
    status: "upcoming",
    coverage: "Full",
    whyWatch: "A Round 1 running back and a 40-mph gusting wind off the coast that could turn this into a ground game.",
    whyWatchReasons: [
      "Boise State's running back is the highest-graded back on 2027 boards.",
      "Oregon State's left tackle is a three-year starter on Day 2 boards.",
      "Sustained 24-mph wind. Field goals beyond 40 yards and any deep shot into the wind are in doubt.",
    ],
    styleLine: "Run-heavy vs run-heavy, wind",
    weather: { windMph: 24, gustMph: 38, windDir: "NW", crosswind: true, precipChance: 55, precipWindow: "after 11 PM", tempF: 52, feelsLikeF: 46, humidity: 82, stormRisk: "none", roof: "open", surface: "turf", elevationFt: 236, asOf: AS_OF },
    market: { spread: { team: "BSU", line: -7, open: -6.5 }, total: { line: 44.5, open: 49 }, books: 9, asOf: "2026-09-12T11:40:00-04:00" },
    prospects: [
      { id: "p-bsu-1", name: "Isaiah Mbeki", team: "BSU", jersey: 28, pos: "RB", cls: "Jr", ht: "5-10", wt: 218, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 1-2", sourceCount: 9, projectionConfidence: "High", traits: ["Contact balance", "Vision on zone"], weakness: "Receiving volume", watchFor: "Carries after the first 15; his yards after contact climb late.", stat: "312 yds, 4 TD" },
      { id: "p-orst-1", name: "Callum Baird", team: "ORST", jersey: 77, pos: "OT", cls: "Sr", ht: "6-6", wt: 315, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 2-3", sourceCount: 6, projectionConfidence: "Medium", traits: ["Run-block finish"], weakness: "Speed to the edge", watchFor: "Reach blocks on outside zone away from the wind.", stat: "1 pressure allowed" },
      { id: "p-bsu-2", name: "Tanner Whitlock", team: "BSU", jersey: 18, pos: "S", cls: "Jr", ht: "6-1", wt: 202, draftYear: 2028, eligibilityConfidence: "Medium", tier: "Future", projected: "Not yet eligible", sourceCount: 2, projectionConfidence: "Low", traits: ["Range"], watchFor: "Deep-half alignment when Oregon State goes play-action.", stat: "1 INT" },
    ],
    matchups: [{ a: "Isaiah Mbeki (BSU RB)", b: "Oregon State run front", why: "A Round 1 back against a defense stuffing 27% of runs.", evidence: "Oregon State plays a 7-man box on 58% of early downs." }],
    keepAnEyeOn: [{ name: "Levi Aumua", team: "ORST", note: "Sophomore nose tackle, 335 pounds, 2028 eligible." }],
    storylines: ["Both teams' kickers have missed from beyond 45 this season; the wind makes that relevant."],
    offense: {
      BSU: { label: "Zone run, play-action", passRate: 44, neutralPassRate: 47, secondsPerPlay: 27.9, structure: "Pro-style spread, 11 and 12", runGame: "Outside zone, inside zone", passGame: "Play-action, boot", successRate: 52, explosiveRate: 13, pressureAllowed: 17, sample: "small" },
      ORST: { label: "Power run, boot", passRate: 43, neutralPassRate: 46, secondsPerPlay: 28.8, structure: "Pro-style, 12 and 21", runGame: "Power, counter", passGame: "Boot, play-action", successRate: 46, explosiveRate: 9, pressureAllowed: 21, sample: "small" },
    },
    defense: {
      BSU: { label: "Even front, single-high", front: "Even, 4-2-5", coverage: "Single-high", blitzRate: 26, pressureRate: 34, stuffRate: 21, explosivesAllowed: 10, sample: "small" },
      ORST: { label: "Heavy box", front: "Odd, 3-4", coverage: "Single-high, 7-man box", blitzRate: 24, pressureRate: 30, stuffRate: 27, explosivesAllowed: 12, sample: "small" },
    },
    pressurePoint: "Two run-first teams in a 24-mph wind. The total has fallen 4.5 points, which correlates with the forecast but is not proof the wind caused the move. Whichever team wins the sideline choice and runs with the wind in the fourth quarter has an edge.",
    scoreComponents: { draftTalent: 72, directMatchups: 68, futureTalent: 50, competitive: 60, styleContrast: 25, storylines: 40, availability: 75 },
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "stan-sjsu",
    division: "FBS",
    away: T("stan", "Stanford Cardinal", "Stanford", "STAN", "0-2", "ACC", "#8C1515"),
    home: T("sjsu", "San José State Spartans", "San José State", "SJSU", "1-1", "Mountain West", "#0055A2"),
    kickoff: "2026-09-12T22:30:00-04:00",
    venue: "CEFCU Stadium",
    city: "San José, CA",
    network: "FS1",
    status: "upcoming",
    coverage: "Full",
    whyWatch: "Stanford's tight end is the only Day 2 name here, and San José State's slot receiver is a sleeper worth a look.",
    whyWatchReasons: ["Stanford tight end is a Round 3 name with Y and H versatility.", "San José State's slot receiver has the best separation numbers in the Mountain West.", "Nothing else on the slate after 10:30 PM outside Boise State."],
    styleLine: "Pro-style vs air raid",
    weather: { windMph: 7, gustMph: 11, windDir: "NW", crosswind: false, precipChance: 0, tempF: 64, feelsLikeF: 64, humidity: 60, stormRisk: "none", roof: "open", surface: "turf", elevationFt: 85, asOf: AS_OF },
    market: { spread: { team: "SJSU", line: -2.5, open: -1 }, total: { line: 56.5, open: 55.5 }, books: 8, asOf: "2026-09-12T11:40:00-04:00" },
    prospects: [
      { id: "p-stan-1", name: "Miles Okonjo", team: "STAN", jersey: 88, pos: "TE", cls: "Sr", ht: "6-5", wt: 248, draftYear: 2027, eligibilityConfidence: "High", tier: "Established", projected: "Round 3", sourceCount: 6, projectionConfidence: "Medium", traits: ["Route running", "Versatility"], weakness: "In-line blocking strength", watchFor: "Alignments: Y, H, and split wide.", stat: "12 rec, 160 yds" },
      { id: "p-sjsu-1", name: "Eli Fonoti", team: "SJSU", jersey: 4, pos: "WR", cls: "Sr", ht: "5-11", wt: 188, draftYear: 2027, eligibilityConfidence: "High", tier: "Sleeper", projected: "Round 6 to UDFA", sourceCount: 2, projectionConfidence: "Low", traits: ["Separation"], weakness: "Size", watchFor: "Wins against Stanford's nickel on option routes.", stat: "19 rec" },
    ],
    matchups: [{ a: "Miles Okonjo (STAN TE)", b: "SJSU safeties", why: "A versatile tight end against a defense that has struggled to match tight ends in motion.", evidence: "SJSU allowed 9 catches to tight ends in week 2." }],
    keepAnEyeOn: [],
    storylines: ["Stanford is 0-2 for the first time since 2019."],
    offense: {
      STAN: { label: "Pro-style, 12 personnel", passRate: 50, neutralPassRate: 52, secondsPerPlay: 28.0, structure: "Pro-style, 12 personnel", runGame: "Outside zone", passGame: "Play-action, TE-heavy", successRate: 42, explosiveRate: 9, pressureAllowed: 31, sample: "small" },
      SJSU: { label: "Air raid", passRate: 64, neutralPassRate: 66, secondsPerPlay: 23.4, structure: "Air raid, 10 personnel", runGame: "Draw, inside zone", passGame: "Mesh, verticals, screens", successRate: 47, explosiveRate: 14, pressureAllowed: 26, sample: "small" },
    },
    defense: {
      STAN: { label: "Two-high", front: "Even", coverage: "Two-high", blitzRate: 21, pressureRate: 27, stuffRate: 17, explosivesAllowed: 15, sample: "small" },
      SJSU: { label: "Single-high", front: "Even, 4-2-5", coverage: "Single-high", blitzRate: 29, pressureRate: 31, stuffRate: 18, explosivesAllowed: 13, sample: "small" },
    },
    pressurePoint: "Stanford's 31% pressure allowed against a modest SJSU rush. If Stanford protects, Okonjo gets targets down the seam.",
    scoreComponents: { draftTalent: 45, directMatchups: 50, futureTalent: 30, competitive: 70, styleContrast: 70, storylines: 30, availability: 75 },
    reportAsOf: AS_OF,
    source: "sample",
  },
  {
    id: "morn-gv",
    division: "NAIA",
    away: T("morn", "Morningside Mustangs", "Morningside", "MORN", "2-0", "GPAC", "#8B1E3F"),
    home: T("gv", "Grand View Vikings", "Grand View", "GV", "2-0", "Heart", "#C41E3A"),
    kickoff: "2026-09-12T20:00:00-04:00",
    venue: "Williams Stadium",
    city: "Des Moines, IA",
    network: "Local stream",
    status: "upcoming",
    coverage: "Limited",
    whyWatch: "Two NAIA national champions. No NFL projections on file; the report explains what data is missing.",
    whyWatchReasons: ["Both programs have won an NAIA title in the last five years.", "Morningside's passing offense has led the NAIA in yards per game for three seasons.", "Limited coverage: schedule and roster are verified; nothing else is."],
    styleLine: "Air raid vs run-heavy",
    weather: { windMph: 13, gustMph: 19, windDir: "S", crosswind: false, precipChance: 30, tempF: 79, feelsLikeF: 81, humidity: 62, stormRisk: "none", roof: "open", surface: "turf", elevationFt: 955, asOf: AS_OF },
    market: { asOf: AS_OF },
    prospects: [],
    matchups: [],
    keepAnEyeOn: [{ name: "Hunter Lindqvist", team: "MORN", note: "Senior quarterback, three-year starter. No projection on file." }],
    storylines: ["Grand View has won 19 straight at home."],
    offense: {
      MORN: { label: "Air raid", passRate: 0, neutralPassRate: 0, secondsPerPlay: 0, structure: "Air raid", runGame: "Unavailable", passGame: "Unavailable", successRate: 0, explosiveRate: 0, pressureAllowed: 0, sample: "unavailable" },
      GV: { label: "Run-heavy", passRate: 0, neutralPassRate: 0, secondsPerPlay: 0, structure: "Pro-style", runGame: "Unavailable", passGame: "Unavailable", successRate: 0, explosiveRate: 0, pressureAllowed: 0, sample: "unavailable" },
    },
    defense: {
      MORN: { label: "Unavailable", front: "Unavailable", coverage: "Unavailable", blitzRate: 0, pressureRate: 0, stuffRate: 0, explosivesAllowed: 0, sample: "unavailable" },
      GV: { label: "Unavailable", front: "Unavailable", coverage: "Unavailable", blitzRate: 0, pressureRate: 0, stuffRate: 0, explosivesAllowed: 0, sample: "unavailable" },
    },
    pressurePoint: "Tendency metrics unavailable. Style labels from program history only.",
    scoreComponents: { draftTalent: 5, directMatchups: 5, futureTalent: 15, competitive: 85, styleContrast: 65, storylines: 60, availability: 35 },
    gaps: ["No play-by-play feed.", "No betting market.", "No published NFL projections.", "Roster verified from school site on 9/9."],
    reportAsOf: AS_OF,
    source: "sample",
  },
];

export function getGame(id: string) {
  return games.find((g) => g.id === id);
}

export function getPlayer(id: string) {
  for (const g of games) {
    const p = g.prospects.find((x) => x.id === id);
    if (p) return { player: p, game: g };
  }
  return undefined;
}

export const SLATE_DATE = "2026-09-12";
